git add ExperimentsResults.tex
git add LiteratureReview.tex
git add do-kth-ex.sh
git add kth-abs.tex
git add kth-ex1.tex
git add kth-mag.cls
git add kth_cmyk.eps
git add kth_cmyk_comp_science_comm.eps
git add kth_cmyk_datavet_komm.eps
git add kth_eng_cmyk.eps
git add kth_eng_pms.eps
git add kth_eng_svv.eps
git add kth_num_analys_cmyk.eps
git add kth_num_analys_pms.eps
git add kth_num_analys_svv.eps
git add kth_num_analysis_cmyk.eps
git add kth_num_analysis_pms.eps
git add kth_num_analysis_svv.eps
git add kth_pms.eps
git add kth_pms_comp_science_comm.eps
git add kth_pms_datavet_komm.eps
git add kth_svv.eps
git add kth_svv_comp_science_comm.eps
git add kth_svv_datavet_komm.eps
git add kthesis.cls
git add kthspik.cls
git add nada-ex.sty
